### ISSUE TITLE
Add the Binary Search algorithm in Cpp

### ISSUE THREAD

**Issue by ashwanitr001** [ashwanitr001/Data_structures-and-Algorithms#1]
**Is your feature request related to a problem? Please describe.**
* This repo has the implemented of Binary Search in Python, to support other people Please write your implementation in language of your choice

**Comment by suyashky** [comment]
Should I add recursive and iterative both or any one of them?

**Comment by suyashky** [comment]
Added recursive and iterative both.

**Comment by ashwanitr001** [comment]
Okay, I'll go through the implementations
